In [12]:
import pandas as pd
import numpy as np
from preprocessing import preprocessings

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sklearn.metrics import mean_squared_error

In [2]:
housing = pd.read_csv('files/housing.csv')
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [3]:
# train test split
housing_train,housing_test=train_test_split(housing,test_size=0.2,stratify=housing['ocean_proximity'],random_state=42)

In [63]:
# target and feature dataset
x_train=housing_train.drop(['median_house_value'],axis=1)
y_train=housing_train['median_house_value']
x_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
2931,-121.88,38.00,22.0,721.0,117.0,367.0,129.0,5.3098,INLAND
4175,-117.82,33.85,18.0,1810.0,305.0,1189.0,326.0,5.2227,<1H OCEAN
12703,-118.31,34.09,34.0,2065.0,839.0,2626.0,775.0,1.8214,<1H OCEAN
16281,-120.76,38.60,14.0,2925.0,625.0,1226.0,437.0,2.5865,INLAND
12420,-118.09,33.92,36.0,847.0,185.0,713.0,194.0,4.8542,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
3666,-118.21,34.13,52.0,2465.0,611.0,1433.0,570.0,3.2500,<1H OCEAN
17452,-122.88,38.34,20.0,3404.0,628.0,1641.0,585.0,5.0574,<1H OCEAN
3006,-118.03,33.90,36.0,1143.0,193.0,826.0,188.0,5.3184,<1H OCEAN
3297,-118.36,34.09,36.0,1390.0,458.0,874.0,468.0,2.5812,<1H OCEAN
19932,-118.11,33.79,36.0,1993.0,354.0,884.0,337.0,5.5870,<1H OCEAN

In [5]:
random_forest=Pipeline([
    ("preprocessing",preprocessings),
    ("randomforest",RandomForestRegressor(random_state=42))
])

In [64]:
random_forest.fit(x_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder=Pipeline(steps=[('impute',
                                                              SimpleImputer(strategy='median')),
                                                             ('scale',
                                                              StandardScaler())]),
                                   transformers=[('bedrooms',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('ratio',
                                                                   FunctionTransformer(feature_names_out=<function column_name at 0x000001DFBC57A820>,
                                                                                       func=<function ratio at 0x0...
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('similarity',
                                                                   FunctionTransformer(feature_names_out=<function similarity_clms at 0x000001DFBC7E0F60>,
                                                                                       func=<function rbf_kernel at 0x000001DFBB4FD010>,
                                                                                       kw_args={'Y': [[35]],
                                                                                                'gamma': 0.1})),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age'])])),
                ('randomforest', RandomForestRegressor(random_state=42))])

In [65]:
random_forest.predict(x_train)

array([159251., 225595., 214084., ..., 180980., 226235., 247864.],
      shape=(16512,))

#### Fine Tune the Model

In [27]:
# from sklearn.model_selection import GridSearchCV


# 13 combinations
param_grid=[
    {
    "preprocessing__geo__n_clusters":[12,15], # 2*2 combinations
    "randomforest__max_features":[8,10]
    },
    {
    "preprocessing__geo__n_clusters":[5,8,10], # 3*3 combinations
    "randomforest__max_features":[4,6,8]
    }
    
]

In [26]:
grid_search=GridSearchCV(
    random_forest,
    param_grid,
    scoring="neg_root_mean_squared_error",
    cv=3,
    refit=True
)

In [30]:
# hyperparameter Tunning, Parameter Tunning --> fine tune the model
grid_search.fit(x_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder=Pipeline(steps=[('impute',
                                                                                     SimpleImputer(strategy='median')),
                                                                                    ('scale',
                                                                                     StandardScaler())]),
                                                          transformers=[('bedrooms',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('ratio',
                                                                                          FunctionTransformer(feature_names_out=<function column_name at 0x000001DFBC57A8...
                                                                                                              kw_args={'Y': [[35]],
                                                                                                                       'gamma': 0.1})),
                                                                                         ('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['housing_median_age'])])),
                                       ('randomforest',
                                        RandomForestRegressor(random_state=42))]),
             param_grid=[{'preprocessing__geo__n_clusters': [12, 15],
                          'randomforest__max_features': [8, 10]},
                         {'preprocessing__geo__n_clusters': [5, 8, 10],
                          'randomforest__max_features': [4, 6, 8]}],
             scoring='neg_root_mean_squared_error')

In [32]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_preprocessing__geo__n_clusters,param_randomforest__max_features,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,13.242047,0.655064,0.487198,0.041130,12,8,"{'preprocessing__geo__n_clusters': 12, 'random...",-46346.576457,-43655.540588,-43525.489551,-44509.202199,1300.304180,4
1,17.407604,2.221760,0.447554,0.069923,12,10,"{'preprocessing__geo__n_clusters': 12, 'random...",-46534.542860,-44521.059605,-44436.230276,-45163.944247,969.778127,9
2,12.928248,1.510530,0.383115,0.017755,15,8,"{'preprocessing__geo__n_clusters': 15, 'random...",-45731.752627,-43348.133192,-42897.396409,-43992.427409,1243.578190,1
3,14.862081,1.512603,0.377265,0.111118,15,10,"{'preprocessing__geo__n_clusters': 15, 'random...",-46134.307039,-43961.016895,-43668.952211,-44588.092049,1099.821514,5
4,7.225958,0.467751,0.309242,0.046916,5,4,"{'preprocessing__geo__n_clusters': 5, 'randomf...",-48144.371400,-45879.219484,-45963.054951,-46662.215278,1048.601346,12
5,10.268210,0.944009,0.296979,0.045316,5,6,"{'preprocessing__geo__n_clusters': 5, 'randomf...",-47859.476665,-46109.929282,-45890.474282,-46619.960076,881.037704,11
6,13.350013,0.983195,0.506989,0.086618,5,8,"{'preprocessing__geo__n_clusters': 5, 'randomf...",-48807.644317,-46398.978029,-46353.369755,-47186.664034,1146.357372,13
7,10.347901,2.229356,0.475570,0.110725,8,4,"{'preprocessing__geo__n_clusters': 8, 'randomf...",-47022.475005,-44179.905865,-43962.609323,-45054.996731,1394.042686,7
8,16.307512,1.647680,0.469270,0.046968,8,6,"{'preprocessing__geo__n_clusters': 8, 'randomf...",-46894.478095,-44272.225185,-44058.239358,-45074.980879,1289.541281,8
9,21.728634,0.357556,0.556281,0.020080,8,8,"{'preprocessing__geo__n_clusters': 8, 'randomf...",-47570.654268,-45145.246067,-44691.678207,-45802.526181,1263.893100,10
10,11.886707,2.837775,0.502422,0.115921,10,4,"{'preprocessing__geo__n_clusters': 10, 'random...",-46607.705981,-43238.387637,-42899.633769,-44248.575796,1673.879719,2
11,16.563841,0.727172,0.477347,0.099505,10,6,"{'preprocessing__geo__n_clusters': 10, 'random...",-46243.215193,-43403.960832,-43212.290896,-44286.488973,1385.825257,3
12,12.908804,0.479708,0.398036,0.017286,10,8,"{'preprocessing__geo__n_clusters': 10, 'random...",-46686.542281,-44389.685700,-43954.931202,-45010.386395,1198.436978,6

In [34]:
grid_search.best_params_

{'preprocessing__geo__n_clusters': 15, 'randomforest__max_features': 8}

#### GridSearchCV fine for fewer combinations, for higher combinations it is compuatationally expensinve

## RandomizedSearchCV for higher 

par --> 8 <br>
space --> 5 <br>
8*5

In [66]:
from scipy.stats import randint

param_distribs={
    "preprocessing__geo__n_clusters":randint(low=3,high=100), # 2*2 combinations
    "randomforest__max_features":randint(low=2,high=20)
    }

In [67]:
from sklearn.model_selection import RandomizedSearchCV
rnd_search=RandomizedSearchCV(random_forest,
    param_distributions=param_distribs,
    n_iter=10,
    cv=3,
    scoring="neg_root_mean_squared_error",
    random_state=42,
    refit=True
    )

In [68]:
rnd_search.fit(x_train,y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(remainder=Pipeline(steps=[('impute',
                                                                                           SimpleImputer(strategy='median')),
                                                                                          ('scale',
                                                                                           StandardScaler())]),
                                                                transformers=[('bedrooms',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('ratio',
                                                                                                FunctionTransformer(feature_names_out=<function column_name at 0x000001DF...
                                             ('randomforest',
                                              RandomForestRegressor(random_state=42))]),
                   param_distributions={'preprocessing__geo__n_clusters': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001DFBC988B00>,
                                        'randomforest__max_features': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001DFBC971010>},
                   random_state=42, scoring='neg_root_mean_squared_error')

In [69]:
pd.DataFrame(rnd_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_preprocessing__geo__n_clusters,param_randomforest__max_features,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,25.175413,7.480692,0.374629,0.093399,54,16,"{'preprocessing__geo__n_clusters': 54, 'random...",-43158.122406,-41695.576723,-44115.108599,-42989.602576,994.931430,5
1,20.580570,0.227287,0.492725,0.008451,74,8,"{'preprocessing__geo__n_clusters': 74, 'random...",-42713.395404,-41657.607489,-44212.726476,-42861.243123,1048.348692,4
2,29.382237,0.387892,0.492861,0.019409,85,12,"{'preprocessing__geo__n_clusters': 85, 'random...",-42537.763972,-41434.541203,-43742.181516,-42571.495564,942.392105,3
3,12.500350,0.636589,0.389380,0.090266,77,5,"{'preprocessing__geo__n_clusters': 77, 'random...",-43468.427202,-42820.968702,-45072.200896,-43787.198933,946.299163,9
4,10.384022,1.529005,0.486348,0.007056,26,4,"{'preprocessing__geo__n_clusters': 26, 'random...",-43040.544448,-42068.557398,-44681.423062,-43263.508303,1078.286111,7
5,8.821088,0.287225,0.409917,0.118708,24,3,"{'preprocessing__geo__n_clusters': 24, 'random...",-43439.067072,-42105.755570,-45203.882685,-43582.901775,1268.887760,8
6,26.491770,2.205712,0.392505,0.021791,90,13,"{'preprocessing__geo__n_clusters': 90, 'random...",-42511.515070,-41353.670379,-43617.687004,-42494.290817,924.361158,1
7,9.985203,3.586526,0.257230,0.087200,32,7,"{'preprocessing__geo__n_clusters': 32, 'random...",-42885.839230,-41732.055339,-44604.316195,-43074.070255,1180.125359,6
8,2.582807,0.561711,0.262436,0.103887,4,2,"{'preprocessing__geo__n_clusters': 4, 'randomf...",-49128.689645,-49620.159234,-51352.884808,-50033.911229,953.993035,10
9,24.027844,1.622959,0.351945,0.120243,78,13,"{'preprocessing__geo__n_clusters': 78, 'random...",-42304.913000,-41456.515380,-43796.057990,-42519.162123,967.054607,2

In [70]:
rnd_search.best_params_

{'preprocessing__geo__n_clusters': 90, 'randomforest__max_features': 13}

## Final Model to Launch

In [71]:
final_model=rnd_search.best_estimator_

In [72]:
x_train['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     7309
INLAND        5241
NEAR OCEAN    2126
NEAR BAY      1832
ISLAND           4
Name: count, dtype: int64

In [73]:
x_df_test=x_train[x_train['ocean_proximity']=="ISLAND"]
y_df_test=y_train[x_train['ocean_proximity']=="ISLAND"]
x_df_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
17205,-118.32,33.35,27.0,1675.0,521.0,744.0,331.0,2.1579,ISLAND
9694,-118.33,33.34,52.0,2359.0,591.0,1100.0,431.0,2.8333,ISLAND
15406,-118.48,33.43,29.0,716.0,214.0,422.0,173.0,2.6042,ISLAND
10229,-118.32,33.34,52.0,996.0,264.0,341.0,160.0,2.7361,ISLAND

In [74]:
pred=final_model.predict(x_df_test)
pred

array([435479.02, 410078.  , 325814.01, 435773.03])

In [75]:
y_df_test

17205    450000.0
9694     414700.0
15406    287500.0
10229    450000.0
Name: median_house_value, dtype: float64

#### Evaluating model on test set

In [76]:
x_test=housing_test.drop(['median_house_value'],axis=1)
y_test=housing_test['median_house_value']
x_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
7050,-121.81,38.01,47.0,1942.0,430.0,1074.0,393.0,2.2361,INLAND
18040,-116.05,33.33,17.0,290.0,94.0,135.0,57.0,1.7292,INLAND
19045,-119.76,36.71,29.0,1745.0,441.0,1530.0,391.0,1.5611,INLAND
2724,-122.25,37.80,42.0,4120.0,1065.0,1715.0,1015.0,2.9345,NEAR BAY
464,-121.98,38.34,18.0,3876.0,916.0,2386.0,867.0,2.5938,INLAND
...,...,...,...,...,...,...,...,...,...
11702,-124.17,41.76,20.0,2673.0,538.0,1282.0,514.0,2.4605,NEAR OCEAN
20128,-122.06,36.98,15.0,3385.0,669.0,1571.0,615.0,4.2254,NEAR OCEAN
16143,-122.31,37.94,38.0,2172.0,403.0,945.0,384.0,4.3958,NEAR BAY
9591,-122.47,37.69,30.0,837.0,213.0,606.0,199.0,4.8750,NEAR OCEAN
18688,-121.79,37.38,22.0,3650.0,527.0,1637.0,520.0,5.3774,<1H OCEAN

In [77]:
pred=final_model.predict(x_test)
pred

array([114117.  ,  68213.  ,  54467.  , ..., 195865.  , 276115.  ,
       296996.01], shape=(4128,))

In [78]:
y_test

7050     105100.0
18040     81300.0
19045     44400.0
2724     225000.0
464      129500.0
           ...
11702    105900.0
20128    320900.0
16143    194200.0
9591     258800.0
18688    325600.0
Name: median_house_value, Length: 4128, dtype: float64

In [79]:
final_mse = mean_squared_error(y_test, pred)
final_rmse=np.sqrt(final_mse)
final_rmse

np.float64(40734.43769312772)

### Model Evaluation
1. lin_reg ---> 68000 NA
2. tree ---> 0.0 ,65000 NA
3. forest ---> 17000 --> 46586 --> 40734

# Approved for Launch

### System Improvements Required
1. specific error analyse
2. add extra feature
3. remove uninformative attribute
4. outlier, round, cap